export default [
  {
    redirect: '/1148141433837666304',
    path: '/1148141432109613056',
    component: 'LAYOUT',
    children: [
      {
        redirect: '/sys/empUser/index',
        path: '/1148141433837666304',
        component: 'LAYOUT',
        children: [
          {
            path: '/sys/empUser/index',
            component: '/sys/empUser/index',
            children: [
              {
                path: '/1148141434491977728',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '查看',
                },
                name: 'Views1148141434491977728',
                id: '1148141434491977728',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/1148141434802356224',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '编辑',
                },
                name: 'Views1148141434802356224',
                id: '1148141434802356224',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/1148141435372781568',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '分配数据',
                },
                name: 'Views1148141435372781568',
                id: '1148141435372781568',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/1148141435087568896',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '分配角色',
                },
                name: 'Views1148141435087568896',
                id: '1148141435087568896',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/1148141435624439808',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '停用启用',
                },
                name: 'Views1148141435624439808',
                id: '1148141435624439808',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/1148141435922235392',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '重置密码',
                },
                name: 'Views1148141435922235392',
                id: '1148141435922235392',
                leaf: true,
                url: '',
                target: '',
              },
            ],
            meta: {
              icon: 'icon-user',
              hideMenu: false,
              color: '',
              title: '用户管理',
            },
            name: 'ViewsSysEmpUserIndex',
            id: '1148141434169016320',
            leaf: false,
            url: '/sys/empUser/index',
            target: '',
          },
          {
            path: '/sys/office/index',
            component: '/sys/office/index',
            children: [
              {
                path: '/1148141436555575296',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '查看',
                },
                name: 'Views1148141436555575296',
                id: '1148141436555575296',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/1148141436815622144',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '编辑',
                },
                name: 'Views1148141436815622144',
                id: '1148141436815622144',
                leaf: true,
                url: '',
                target: '',
              },
            ],
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '机构管理',
            },
            name: 'ViewsSysOfficeIndex',
            id: '1148141436257779712',
            leaf: false,
            url: '/sys/office/index',
            target: '',
          },
          {
            path: '/sys/company/index',
            component: '/sys/company/index',
            children: [
              {
                path: '/1148141437235052544',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '查看',
                },
                name: 'Views1148141437235052544',
                id: '1148141437235052544',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/1148141437432184832',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '编辑',
                },
                name: 'Views1148141437432184832',
                id: '1148141437432184832',
                leaf: true,
                url: '',
                target: '',
              },
            ],
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: 'icon-fire',
              hideMenu: false,
              color: '',
              title: '公司管理',
            },
            name: 'ViewsSysCompanyIndex',
            id: '1148141437042114560',
            leaf: false,
            url: '/sys/company/index',
            target: '',
          },
          {
            path: '/sys/post/list',
            component: '/sys/post/list',
            children: [
              {
                path: '/1148141437906141184',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '查看',
                },
                name: 'Views1148141437906141184',
                id: '1148141437906141184',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/1148141438141022208',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '编辑',
                },
                name: 'Views1148141438141022208',
                id: '1148141438141022208',
                leaf: true,
                url: '',
                target: '',
              },
            ],
            meta: {
              icon: 'icon-trophy',
              hideMenu: false,
              color: '',
              title: '岗位管理',
            },
            name: 'ViewsSysPostList',
            id: '1148141437688037376',
            leaf: false,
            url: '/sys/post/list',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '组织管理',
        },
        name: 'Views1148141433837666304',
        id: '1148141433837666304',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: '/sys/role/list',
        path: '/1148141438350737408',
        component: 'LAYOUT',
        children: [
          {
            path: '/sys/role/list',
            component: '/sys/role/list',
            meta: {
              icon: 'icon-people',
              hideMenu: false,
              color: '',
              title: '角色管理',
            },
            name: 'ViewsSysRoleList',
            id: '1148141438510120960',
            leaf: true,
            url: '/sys/role/list',
            target: '',
          },
          {
            path: '/sys/secAdmin/list',
            component: '/sys/secAdmin/list',
            meta: {
              icon: 'icon-user-female',
              hideMenu: false,
              color: '',
              title: '二级管理员',
            },
            name: 'ViewsSysSecAdminList',
            id: '1148141438581424128',
            leaf: true,
            url: '/sys/secAdmin/list',
            target: '',
          },
          {
            path: '/sys/corpAdmin/list',
            component: '/sys/corpAdmin/list',
            meta: {
              icon: 'icon-badge',
              hideMenu: false,
              color: '',
              title: '租户管理员',
            },
            name: 'ViewsSysCorpAdminList',
            id: '1148141438661115904',
            leaf: true,
            url: '/sys/corpAdmin/list',
            target: '',
          },
          {
            path: '/sys/audit/list',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: 'icon-energy',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/sys/audit/list',
              title: '安全审计',
            },
            name: 'ViewsSysAuditList',
            id: '1238121573028433920',
            leaf: true,
            url: '/sys/audit/list',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-social-dropbox',
          hideMenu: false,
          color: '',
          title: '权限管理',
        },
        name: 'Views1148141438350737408',
        id: '1148141438350737408',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: '/sys/menu/index',
        path: '/1148141438736613376',
        component: 'LAYOUT',
        children: [
          {
            path: '/sys/menu/index',
            component: '/sys/menu/index',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: 'icon-book-open',
              hideMenu: false,
              color: '',
              title: '菜单管理',
            },
            name: 'ViewsSysMenuIndex',
            id: '1148141438824693760',
            leaf: true,
            url: '/sys/menu/index',
            target: '',
          },
          {
            path: '/sys/module/list',
            component: '/sys/module/list',
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '模块管理',
            },
            name: 'ViewsSysModuleList',
            id: '1148141438904385536',
            leaf: true,
            url: '/sys/module/list',
            target: '',
          },
          {
            path: '/sys/config/list',
            component: '/sys/config/list',
            meta: {
              icon: 'icon-wrench',
              hideMenu: false,
              color: '',
              title: '参数设置',
            },
            name: 'ViewsSysConfigList',
            id: '1148141438979883008',
            leaf: true,
            url: '/sys/config/list',
            target: '',
          },
          {
            path: '/sys/dictType/list',
            component: '/sys/dictType/list',
            children: [
              {
                path: '/1148141439139266560',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '类型查看',
                },
                name: 'Views1148141439139266560',
                id: '1148141439139266560',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/1148141439231541248',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '类型编辑',
                },
                name: 'Views1148141439231541248',
                id: '1148141439231541248',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/sys/dictData/list',
                component: '/sys/dictData/list',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '数据查看',
                },
                name: 'ViewsSysDictDataList',
                id: '1148141439315427328',
                leaf: true,
                url: '/sys/dictData/list',
                target: '',
              },
              {
                path: '/1148141439395119104',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '数据编辑',
                },
                name: 'Views1148141439395119104',
                id: '1148141439395119104',
                leaf: true,
                url: '',
                target: '',
              },
            ],
            meta: {
              icon: 'icon-social-dropbox',
              hideMenu: false,
              color: '',
              title: '字典管理',
            },
            name: 'ViewsSysDictTypeList',
            id: '1148141439063769088',
            leaf: false,
            url: '/sys/dictType/list',
            target: '',
          },
          {
            path: '/sys/area/index',
            component: '/sys/area/index',
            meta: {
              icon: 'icon-map',
              hideMenu: false,
              color: '',
              title: '行政区划',
            },
            name: 'ViewsSysAreaIndex',
            id: '1148141439470616576',
            leaf: true,
            url: '/sys/area/index',
            target: '',
          },
          {
            path: '/sys/lang/list',
            component: 'IFRAME',
            meta: {
              icon: 'icon-globe',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/sys/lang/list',
              title: '国际化管理',
            },
            name: 'ViewsSysLangList',
            id: '1148141439550308352',
            leaf: true,
            url: '/sys/lang/list',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-settings',
          hideMenu: false,
          color: '',
          title: '系统设置',
        },
        name: 'Views1148141438736613376',
        id: '1148141438736613376',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: '/sys/log/list',
        path: '/1148141439722274816',
        component: 'LAYOUT',
        children: [
          {
            path: '/sys/log/list',
            component: '/sys/log/list',
            meta: {
              icon: 'fa fa-bug',
              hideMenu: false,
              color: '',
              title: '访问日志',
            },
            name: 'ViewsSysLogList',
            id: '1148141439806160896',
            leaf: true,
            url: '/sys/log/list',
            target: '',
          },
          {
            path: '//druid/index.html',
            component: 'IFRAME',
            meta: {
              icon: 'icon-disc',
              hideMenu: false,
              color: '',
              frameSrc: '/js/druid/index.html',
              title: '数据监控',
            },
            name: 'ViewsDruidIndexHtml',
            id: '1148141439885852672',
            leaf: true,
            url: '//druid/index.html',
            target: '',
          },
          {
            path: '/state/cache/index',
            component: 'IFRAME',
            meta: {
              icon: 'icon-social-dribbble',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/state/cache/index',
              title: '缓存监控',
            },
            name: 'ViewsStateCacheIndex',
            id: '1148141440015876096',
            leaf: true,
            url: '/state/cache/index',
            target: '',
          },
          {
            path: '/state/server/index',
            component: 'IFRAME',
            meta: {
              icon: 'icon-speedometer',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/state/server/index',
              title: '服务器监控',
            },
            name: 'ViewsStateServerIndex',
            id: '1148141440095567872',
            leaf: true,
            url: '/state/server/index',
            target: '',
          },
          {
            path: '/job/list',
            component: 'IFRAME',
            meta: {
              icon: 'icon-notebook',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/job/list',
              title: '作业监控',
            },
            name: 'ViewsJobList',
            id: '1148141440175259648',
            leaf: true,
            url: '/job/list',
            target: '',
          },
          {
            path: '/sys/online/list',
            component: '/sys/online/list',
            meta: {
              icon: 'icon-social-twitter',
              hideMenu: false,
              color: '',
              title: '在线用户',
            },
            name: 'ViewsSysOnlineList',
            id: '1148141440254951424',
            leaf: true,
            url: '/sys/online/list',
            target: '',
          },
          {
            path: '/js/swagger-ui.html?___blank',
            component: 'IFRAME',
            meta: {
              icon: 'icon-book-open',
              hideMenu: false,
              color: '',
              frameSrc: '/js/swagger-ui.html',
              title: '在线文档',
            },
            name: 'ViewsSwaggerUiHtml',
            id: '1148141440334643200',
            leaf: true,
            url: '//swagger-ui.html',
            target: '_blank',
          },
        ],
        meta: {
          icon: 'icon-ghost',
          hideMenu: false,
          color: '',
          title: '系统监控',
        },
        name: 'Views1148141439722274816',
        id: '1148141439722274816',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: '/msg/msgPush/list',
        path: '/1148141440410140672',
        component: 'LAYOUT',
        children: [
          {
            path: '/msg/msgPush/list',
            component: 'IFRAME',
            meta: {
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/msg/msgPush/list',
              title: '未完成消息',
            },
            name: 'ViewsMsgMsgPushList',
            id: '1148141440489832448',
            leaf: true,
            url: '/msg/msgPush/list',
            target: '',
          },
          {
            path: '/msg/msgPush/list-pushed-true',
            component: 'IFRAME',
            meta: {
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/msg/msgPush/list?pushed=true',
              title: '已完成消息',
            },
            name: 'ViewsMsgMsgPushListPushedTrue',
            id: '1148141440565329920',
            leaf: true,
            url: '/msg/msgPush/list?pushed=true',
            target: '',
          },
          {
            path: '/msg/msgTemplate/list',
            component: 'IFRAME',
            meta: {
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/msg/msgTemplate/list',
              title: '消息模板管理',
            },
            name: 'ViewsMsgMsgTemplateList',
            id: '1148141440649216000',
            leaf: true,
            url: '/msg/msgTemplate/list',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-envelope-letter',
          hideMenu: false,
          color: '',
          title: '消息推送',
        },
        name: 'Views1148141440410140672',
        id: '1148141440410140672',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: '/gen/genTable/list',
        path: '/1148141440737296384',
        component: 'LAYOUT',
        children: [
          {
            path: '/gen/genTable/list',
            component: 'IFRAME',
            meta: {
              icon: 'fa fa-code',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/gen/genTable/list',
              title: '代码生成工具',
            },
            name: 'ViewsGenGenTableList',
            id: '1148141440821182464',
            leaf: true,
            url: '/gen/genTable/list',
            target: '',
          },
          {
            redirect: '/test/testData/list',
            path: '/1148141440905068544',
            component: 'LAYOUT',
            children: [
              {
                path: '/test/testData/list',
                component: '/test/testData/list',
                children: [
                  {
                    path: '/test/testData/formRoute',
                    component: '/test/testData/formRoute',
                    meta: {
                      hideMenu: true,
                      title: '数据表单',
                    },
                    name: 'ViewsTestTestDataFormRoute',
                    id: '1687063518407364608',
                    leaf: true,
                    url: '/test/testData/formRoute',
                  },
                ],
                meta: {
                  extend: {
                    extendS4: '',
                    extendS1: '',
                    extendS7: '',
                    extendS2: '',
                    extendS6: '',
                    extendS8: '',
                    extendS5: '',
                    extendS3: '',
                    extendMap: {},
                  },
                  icon: '',
                  hideMenu: false,
                  color: '',
                  title: '单表/主子表',
                },
                name: 'ViewsTestTestDataList',
                id: '1148141440980566016',
                leaf: false,
                url: '/test/testData/list',
                target: '',
              },
              {
                path: '/test/testTree/list',
                component: '/test/testTree/list',
                meta: {
                  extend: {
                    extendS4: '',
                    extendS1: '',
                    extendS7: '',
                    extendS2: '',
                    extendS6: '',
                    extendS8: '',
                    extendS5: '',
                    extendS3: '',
                    extendMap: {},
                  },
                  icon: '',
                  hideMenu: false,
                  color: '',
                  title: '树表/树结构表',
                },
                name: 'ViewsTestTestTreeList',
                id: '1148141441051869184',
                leaf: true,
                url: '/test/testTree/list',
                target: '',
              },
            ],
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: 'icon-social-dropbox',
              hideMenu: false,
              color: '',
              title: '代码生成实例',
            },
            name: 'Views1148141440905068544',
            id: '1148141440905068544',
            leaf: false,
            url: '',
            target: '',
          },
          {
            redirect: '/demo/form/tableForm',
            path: '/1148141441345470464',
            component: 'LAYOUT',
            children: [
              {
                path: '/demo/form/tableForm',
                component: 'IFRAME',
                meta: {
                  icon: '',
                  hideMenu: false,
                  color: '',
                  frameSrc: '/js/a/demo/form/tableForm',
                  title: '表格表单实例',
                },
                name: 'ViewsDemoFormTableForm',
                id: '1148141441580351488',
                leaf: true,
                url: '/demo/form/tableForm',
                target: '',
              },
            ],
            meta: {
              icon: '',
              hideMenu: false,
              color: '',
              title: '表单组件实例',
            },
            name: 'Views1148141441345470464',
            id: '1148141441345470464',
            leaf: false,
            url: '',
            target: '',
          },
        ],
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'fa fa-code',
          hideMenu: false,
          color: '',
          title: '研发工具',
        },
        name: 'Views1148141440737296384',
        id: '1148141440737296384',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: 'http://jeesite.com?___blank',
        path: '/1148141441832009728',
        component: 'LAYOUT',
        children: [
          {
            path: 'http://jeesite.com?___blank',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: 'http://jeesite.com',
              title: '官方网站',
            },
            name: 'ViewsHttpJeesiteCom',
            id: '1148141441911701504',
            leaf: true,
            url: 'http://jeesite.com',
            target: '_blank',
          },
          {
            path: 'https://gitee.com/thinkgem/jeesite4/issues?___blank',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: 'https://gitee.com/thinkgem/jeesite4/issues',
              title: '问题反馈',
            },
            name: 'ViewsHttpsGiteeComThinkgemJeesite4Issues',
            id: '1148141442075279360',
            leaf: true,
            url: 'https://gitee.com/thinkgem/jeesite4/issues',
            target: '_blank',
          },
          {
            path: '/1160478016363282432',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: 'https://jeesite.com/docs/upgrade/',
              title: '更新日志',
            },
            name: 'ViewsHttpsJeesiteComDocsUpgrade',
            id: '1160478016363282432',
            leaf: true,
            url: 'https://jeesite.com/docs/upgrade/',
            target: '',
          },
          {
            path: 'https://gitee.com/thinkgem?___blank',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: 'https://gitee.com/thinkgem',
              title: '最新动态',
            },
            name: 'ViewsHttpsGiteeComThinkgem',
            id: '1160478281887891456',
            leaf: true,
            url: 'https://gitee.com/thinkgem',
            target: '_blank',
          },
          {
            path: '/1148141441991393280',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: 'https://my.oschina.net/thinkgem',
              title: '作者博客',
            },
            name: 'ViewsHttpsMyOschinaNetThinkgem',
            id: '1148141441991393280',
            leaf: true,
            url: 'https://my.oschina.net/thinkgem',
            target: '',
          },
          {
            path: 'http://s.jeesite.com?___blank',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: 'http://s.jeesite.com',
              title: '技术服务',
            },
            name: 'ViewsHttpSJeesiteCom',
            id: '1160479233063763968',
            leaf: true,
            url: 'http://s.jeesite.com',
            target: '_blank',
          },
        ],
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'icon-directions',
          hideMenu: false,
          color: '',
          title: 'JeeSite社区',
        },
        name: 'Views1148141441832009728',
        id: '1148141441832009728',
        leaf: false,
        url: '',
        target: '',
      },
    ],
    meta: {
      icon: 'icon-settings',
      hideMenu: false,
      color: '',
      title: '系统管理',
    },
    name: 'Views1148141432109613056',
    id: '1148141432109613056',
    leaf: false,
    url: '',
    target: '',
  },
  {
    redirect: '/1160482921891217408',
    path: '/1148141442268217344',
    component: 'LAYOUT',
    children: [
      {
        redirect: '/msg/msgInner/list',
        path: '/1160482921891217408',
        component: 'LAYOUT',
        children: [
          {
            path: '/msg/msgInner/list',
            component: '/msg/msgInner/list',
            children: [
              {
                path: '/msg/msgInner/view',
                component: '/msg/msgInner/view',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '查看消息',
                },
                name: 'ViewsMsgMsgInnerView',
                id: '1148141442398240768',
                leaf: true,
                url: '/msg/msgInner/view',
                target: '',
              },
              {
                path: '/1148141442469543936',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '编辑',
                },
                name: 'Views1148141442469543936',
                id: '1148141442469543936',
                leaf: true,
                url: '',
                target: '',
              },
              {
                path: '/1148141442540847104',
                component: '',
                meta: {
                  icon: '',
                  hideMenu: true,
                  color: '',
                  title: '审核',
                },
                name: 'Views1148141442540847104',
                id: '1148141442540847104',
                leaf: true,
                url: '',
                target: '',
              },
            ],
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              title: '站内消息',
            },
            name: 'ViewsMsgMsgInnerList',
            id: '1148141442326937600',
            leaf: false,
            url: '/msg/msgInner/list',
            target: '',
          },
          {
            path: '/msg/msgInner/form',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: true,
              color: '',
              frameSrc: '/js/a/msg/msgInner/form',
              title: '新增消息',
            },
            name: 'ViewsMsgMsgInnerForm',
            id: '1160483147305697280',
            leaf: true,
            url: '/msg/msgInner/form',
            target: '',
          },
        ],
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'icon-speech',
          hideMenu: false,
          color: '',
          title: '站内消息',
        },
        name: 'Views1160482921891217408',
        id: '1160482921891217408',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: '/filemanager/index',
        path: '/1148141442620538880',
        component: 'LAYOUT',
        children: [
          {
            path: '/filemanager/index',
            component: '/filemanager/index',
            meta: {
              icon: '',
              hideMenu: false,
              color: '',
              title: '文件管理',
            },
            name: 'ViewsFilemanagerIndex',
            id: '1148141442691842048',
            leaf: true,
            url: '/filemanager/index',
            target: '',
          },
          {
            path: '/filemanager/filemanagerShared/list',
            component: '/filemanager/filemanagerShared/list',
            meta: {
              icon: '',
              hideMenu: false,
              color: '',
              title: '文件分享',
            },
            name: 'ViewsFilemanagerFilemanagerSharedList',
            id: '1148141442779922432',
            leaf: true,
            url: '/filemanager/filemanagerShared/list',
            target: '',
          },
        ],
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'icon-folder',
          hideMenu: false,
          color: '',
          title: '文件管理',
        },
        name: 'Views1148141442620538880',
        id: '1148141442620538880',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: '/cms/index',
        path: '/1286552693380927488',
        component: 'LAYOUT',
        children: [
          {
            path: '/cms/index',
            component: 'IFRAME',
            meta: {
              icon: 'icon-book-open',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/cms/index',
              title: '内容发布',
            },
            name: 'ViewsCmsIndex',
            id: '1286552701132001280',
            leaf: true,
            url: '/cms/index',
            target: '',
          },
          {
            path: '/cms/category/list',
            component: 'IFRAME',
            meta: {
              icon: 'icon-plus',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/cms/category/list',
              title: '栏目管理',
            },
            name: 'ViewsCmsCategoryList',
            id: '1286552702214131712',
            leaf: true,
            url: '/cms/category/list',
            target: '',
          },
          {
            path: '/cms/site/list',
            component: 'IFRAME',
            meta: {
              icon: 'icon-badge',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/cms/site/list',
              title: '站点设置',
            },
            name: 'ViewsCmsSiteList',
            id: '1286552703325622272',
            leaf: true,
            url: '/cms/site/list',
            target: '',
          },
          {
            path: '/cms/template/list',
            component: 'IFRAME',
            meta: {
              icon: 'icon-graduation',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/cms/template/list',
              title: '模版管理',
            },
            name: 'ViewsCmsTemplateList',
            id: '1286552704520998912',
            leaf: true,
            url: '/cms/template/list',
            target: '',
          },
        ],
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'icon-social-dropbox',
          hideMenu: false,
          color: '',
          title: '内容管理',
        },
        name: 'Views1286552693380927488',
        id: '1286552693380927488',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: '//ureport/designer-_u-file:user.ureport.xml',
        path: '/1160480134239338496',
        component: 'LAYOUT',
        children: [
          {
            path: '//ureport/designer-_u-file:user.ureport.xml',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: 'icon-list',
              hideMenu: false,
              color: '',
              frameSrc: '/js/ureport/designer?_u=file:user.ureport.xml',
              title: '报表设计器',
            },
            name: 'ViewsUreportDesignerUFileUserUreportXml',
            id: '1160480198949060608',
            leaf: true,
            url: '//ureport/designer?_u=file:user.ureport.xml',
            target: '',
          },
          {
            path: '//ureport/preview-_u-file:user.ureport.xml',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: 'icon-event',
              hideMenu: false,
              color: '',
              frameSrc: '/js/ureport/preview?_u=file:user.ureport.xml',
              title: '用户统计例子',
            },
            name: 'ViewsUreportPreviewUFileUserUreportXml',
            id: '1160480296697315328',
            leaf: true,
            url: '//ureport/preview?_u=file:user.ureport.xml',
            target: '',
          },
          {
            path: '/js/visual/index?___blank',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: 'icon-layers',
              hideMenu: false,
              color: '',
              frameSrc: '/js/visual/index',
              title: '可视化数据大屏',
            },
            name: 'ViewsVisualIndex',
            id: '1265975579613220864',
            leaf: true,
            url: '//visual/index',
            target: '_blank',
          },
          {
            path: 'https://echarts.apache.org/examples/zh/index.html?___blank',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: 'icon-pie-chart',
              hideMenu: false,
              color: '',
              frameSrc: 'https://echarts.apache.org/examples/zh/index.html',
              title: '可视化数据图表',
            },
            name: 'ViewsHttpsEchartsApacheOrgExamplesZhIndexHtml',
            id: '1148481273848082432',
            leaf: true,
            url: 'https://echarts.apache.org/examples/zh/index.html',
            target: '_blank',
          },
        ],
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'icon-graph',
          hideMenu: false,
          color: '',
          title: '统计报表',
        },
        name: 'Views1160480134239338496',
        id: '1160480134239338496',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: '/app/appUpgrade/list',
        path: '/1382704182394269696',
        component: 'LAYOUT',
        children: [
          {
            path: '/app/appUpgrade/list',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/app/appUpgrade/list',
              title: 'APP版本管理',
            },
            name: 'ViewsAppAppUpgradeList',
            id: '1382704183216353280',
            leaf: true,
            url: '/app/appUpgrade/list',
            target: '',
          },
          {
            path: '/app/appComment/list',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/app/appComment/list',
              title: 'APP意见反馈',
            },
            name: 'ViewsAppAppCommentList',
            id: '1382704184357203968',
            leaf: true,
            url: '/app/appComment/list',
            target: '',
          },
        ],
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'icon-globe',
          hideMenu: false,
          color: '',
          title: '移动端管理',
        },
        name: 'Views1382704182394269696',
        id: '1382704182394269696',
        leaf: false,
        url: '',
        target: '',
      },
      {
        path: '//oauth2/list',
        component: 'IFRAME',
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'icon-options-vertical',
          hideMenu: false,
          color: '',
          frameSrc: '/js/oauth2/list',
          title: '第三方账号登录',
        },
        name: 'ViewsOauth2List',
        id: '1282896917307056128',
        leaf: true,
        url: '//oauth2/list',
        target: '',
      },
    ],
    meta: {
      extend: {
        extendS4: '',
        extendS1: '',
        extendS7: '',
        extendS2: '',
        extendS6: '',
        extendS8: '',
        extendS5: '',
        extendS3: '',
        extendMap: {},
      },
      icon: 'icon-screen-desktop',
      hideMenu: false,
      color: '',
      title: '扩展功能',
    },
    name: 'Views1148141442268217344',
    id: '1148141442268217344',
    leaf: false,
    url: '',
    target: '',
  },
  {
    redirect: '/1178607869823733760',
    path: '/1160560134136328192',
    component: 'LAYOUT',
    children: [
      {
        redirect: '/bpm/bpmMyTask/todoList',
        path: '/1178607869823733760',
        component: 'LAYOUT',
        children: [
          {
            path: '/bpm/bpmMyTask/todoList',
            component: '/bpm/bpmMyTask/todoList',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              title: '待办任务',
            },
            name: 'ViewsBpmBpmMyTaskTodoList',
            id: '1178608101517086720',
            leaf: true,
            url: '/bpm/bpmMyTask/todoList',
            target: '',
          },
          {
            path: '/bpm/bpmMyTask/historyList',
            component: '/bpm/bpmMyTask/historyList',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              title: '已办任务',
            },
            name: 'ViewsBpmBpmMyTaskHistoryList',
            id: '1178608141228756992',
            leaf: true,
            url: '/bpm/bpmMyTask/historyList',
            target: '',
          },
          {
            path: '/bpm/bpmMyRuntime/list',
            component: '/bpm/bpmMyRuntime/list',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              title: '与我相关流程',
            },
            name: 'ViewsBpmBpmMyRuntimeList',
            id: '1182486331208413184',
            leaf: true,
            url: '/bpm/bpmMyRuntime/list',
            target: '',
          },
          {
            path: '/oa/oaLeave/list',
            component: '/oa/oaLeave/list',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              title: '请假单管理(示例)',
            },
            name: 'ViewsOaOaLeaveList',
            id: '1193447797863182336',
            leaf: true,
            url: '/oa/oaLeave/list',
            target: '',
          },
        ],
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'icon-control-forward',
          hideMenu: false,
          color: '',
          title: '流程办理',
        },
        name: 'Views1178607869823733760',
        id: '1178607869823733760',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: '/bpm/bpmCategory/list',
        path: '/1178607696313765888',
        component: 'LAYOUT',
        children: [
          {
            path: '/bpm/bpmCategory/list',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/bpm/bpmCategory/list',
              title: '流程分类管理',
            },
            name: 'ViewsBpmBpmCategoryList',
            id: '1160909015834836992',
            leaf: true,
            url: '/bpm/bpmCategory/list',
            target: '',
          },
          {
            path: '//bpm/modeler/index.html',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/bpm/modeler/index.html',
              title: '流程模型设计',
            },
            name: 'ViewsBpmModelerIndexHtml',
            id: '1160561379337105408',
            leaf: true,
            url: '//bpm/modeler/index.html',
            target: '',
          },
          {
            path: '/bpm/bpmCategory/index/process',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/bpm/bpmCategory/index/process',
              title: '流程定义管理',
            },
            name: 'ViewsBpmBpmCategoryIndexProcess',
            id: '1160561451588186112',
            leaf: true,
            url: '/bpm/bpmCategory/index/process',
            target: '',
          },
          {
            path: '/bpm/bpmRuntime/list',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/bpm/bpmRuntime/list',
              title: '流程实例管理',
            },
            name: 'ViewsBpmBpmRuntimeList',
            id: '1167462662778339328',
            leaf: true,
            url: '/bpm/bpmRuntime/list',
            target: '',
          },
          {
            path: '/bpm/bpmTask/list',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/bpm/bpmTask/list',
              title: '流程任务管理',
            },
            name: 'ViewsBpmBpmTaskList',
            id: '1178607437361631232',
            leaf: true,
            url: '/bpm/bpmTask/list',
            target: '',
          },
          {
            path: '/bpm/bpmScript/list',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '/js/a/bpm/bpmScript/list',
              title: '流程脚本管理',
            },
            name: 'ViewsBpmBpmScriptList',
            id: '1200015159863119872',
            leaf: true,
            url: '/bpm/bpmScript/list',
            target: '',
          },
        ],
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'icon-paypal',
          hideMenu: false,
          color: '',
          title: '流程管控',
        },
        name: 'Views1178607696313765888',
        id: '1178607696313765888',
        leaf: false,
        url: '',
        target: '',
      },
      {
        redirect: 'http://101.42.243.212:7050/js?___blank',
        path: '/1160497519243542528',
        component: 'IFRAME',
        children: [
          {
            path: 'http://101.42.243.212:7050/js?___blank',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: 'http://101.42.243.212:7050/js',
              title: 'JFlow 工作流',
            },
            name: 'ViewsHttp101422432127050Js',
            id: '1160497635861970944',
            leaf: true,
            url: 'http://101.42.243.212:7050/js',
            target: '_blank',
          },
          {
            path: '/1160497679432400896',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '',
              title: '账号：system',
            },
            name: 'Views1160497679432400896',
            id: '1160497679432400896',
            leaf: true,
            url: '',
            target: '',
          },
          {
            path: '/1160497708620562432',
            component: 'IFRAME',
            meta: {
              extend: {
                extendS4: '',
                extendS1: '',
                extendS7: '',
                extendS2: '',
                extendS6: '',
                extendS8: '',
                extendS5: '',
                extendS3: '',
                extendMap: {},
              },
              icon: '',
              hideMenu: false,
              color: '',
              frameSrc: '',
              title: '密码：admin',
            },
            name: 'Views1160497708620562432',
            id: '1160497708620562432',
            leaf: true,
            url: '',
            target: '',
          },
        ],
        meta: {
          extend: {
            extendS4: '',
            extendS1: '',
            extendS7: '',
            extendS2: '',
            extendS6: '',
            extendS8: '',
            extendS5: '',
            extendS3: '',
            extendMap: {},
          },
          icon: 'icon-direction',
          hideMenu: true,
          color: '',
          frameSrc: '',
          title: 'JFlow版本',
        },
        name: 'Views1160497519243542528',
        id: '1160497519243542528',
        leaf: false,
        url: '',
        target: '',
      },
    ],
    meta: {
      extend: {
        extendS4: '',
        extendS1: '',
        extendS7: '',
        extendS2: '',
        extendS6: '',
        extendS8: '',
        extendS5: '',
        extendS3: '',
        extendMap: {},
      },
      icon: 'icon-social-foursqare',
      hideMenu: false,
      color: '',
      title: '业务流程',
    },
    name: 'Views1160560134136328192',
    id: '1160560134136328192',
    leaf: false,
    url: '',
    target: '',
  },
  {
    path: 'https://demo.jeesite.com?___blank',
    component: 'IFRAME',
    meta: {
      icon: 'icon-fire',
      hideMenu: false,
      frameSrc: 'https://demo.jeesite.com',
      title: 'V4.x 演示',
    },
    name: 'ViewsHttpsDemoJeesiteCom',
    id: '1509183548334575616',
    leaf: true,
    url: 'https://demo.jeesite.com',
    target: '_blank',
  },
  {
    path: '/desktop/workbench',
    component: 'LAYOUT',
    meta: {
      extend: {
        extendS4: '',
        extendS1: '',
        extendS7: '',
        extendS2: '',
        extendS6: '',
        extendS8: '',
        extendS5: '',
        extendS3: '',
        extendMap: {},
      },
      icon: 'icon-screen-desktop',
      hideMenu: false,
      color: '',
      title: '我的工作',
    },
    name: 'ViewsDesktopWorkbench',
    id: '1469547181535264770',
    leaf: true,
    url: '/desktop/workbench',
    target: '',
  },
  {
    path: '/desktop/about',
    component: 'LAYOUT',
    meta: {
      extend: {
        extendS4: '',
        extendS1: '',
        extendS7: '',
        extendS2: '',
        extendS6: '',
        extendS8: '',
        extendS5: '',
        extendS3: '',
        extendMap: {},
      },
      icon: 'icon-tag',
      hideMenu: false,
      color: '',
      title: '关于我们',
    },
    name: 'ViewsDesktopAbout',
    id: '1469547181535264769',
    leaf: true,
    url: '/desktop/about',
    target: '',
  },
  {
    path: '/1148141442167554048',
    component: 'IFRAME',
    meta: {
      extend: {
        extendS4: '',
        extendS1: '',
        extendS7: '',
        extendS2: '',
        extendS6: '',
        extendS8: '',
        extendS5: '',
        extendS3: '',
        extendMap: {},
      },
      icon: 'icon-graduation',
      hideMenu: false,
      color: '',
      frameSrc: 'https://jeesite.com/docs',
      title: '在线文档',
    },
    name: 'ViewsHttpsJeesiteComDocs',
    id: '1148141442167554048',
    leaf: true,
    url: 'https://jeesite.com/docs',
    target: '',
  },
];
