export default [
  {
    path: '/system',
    redirect: '/sys/tenant/list',
    name: '系统管理',
    component: 'LAYOUT',
    meta: {
      icon: 'icon-settings',
      hideMenu: false,
      color: '',
      title: '系统管理',
    },
    children: [
      {
        path: '/sys/tenant/list',
        component: '/sys/tenant/list',
        children: [],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '租户管理',
        },
        name: 'ViewsSysTenantList',
        leaf: false,
        url: '/sys/tenant/list',
        target: '',
      },
      {
        path: '/sys/user/index',
        component: '/sys/user/index',
        children: [],
        meta: {
          icon: 'icon-user',
          hideMenu: false,
          color: '',
          title: '用户管理',
        },
        name: 'ViewsSysuserIndex',
        leaf: false,
        url: '/sys/user/index',
        target: '',
      },
      {
        path: '/sys/role/list',
        component: '/sys/role/list',
        meta: {
          icon: 'icon-people',
          hideMenu: false,
          color: '',
          title: '角色管理',
        },
        name: 'ViewsSysRoleList',
        leaf: true,
        url: '/sys/role/list',
        target: '',
      },
      {
        path: '/sys/menu/index',
        component: '/sys/menu/index',
        meta: {
          icon: 'icon-book-open',
          hideMenu: false,
          color: '',
          title: '菜单管理',
        },
        name: 'ViewsSysMenuIndex',
        leaf: true,
        url: '/sys/menu/index',
        target: '',
      },
      {
        path: '/sys/dictType/list',
        component: '/sys/dictType/list',
        children: [
          {
            path: '/sys/dictData/list',
            component: '/sys/dictData/list',
            meta: {
              icon: '',
              hideMenu: true,
              color: '',
              title: '数据查看',
            },
            name: 'ViewsSysDictDataList',
            leaf: true,
            url: '/sys/dictData/list',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-social-dropbox',
          hideMenu: false,
          color: '',
          title: '字典管理',
        },
        name: 'ViewsSysDictTypeList',
        leaf: false,
        url: '/sys/dictType/list',
        target: '',
      },
    ],
    leaf: false,
    url: '',
    target: '',
  },
  {
    path: '/seller',
    redirect: '/seller/app',
    name: '商家中心',
    component: 'LAYOUT',
    meta: {
      icon: 'icon-settings',
      hideMenu: false,
      color: '',
      title: '商家中心',
    },
    children: [
      {
        path: '/seller/app',
        redirect: '/seller/app/home/index',
        component: 'LAYOUT',
        children: [
          {
            path: '/seller/app/home/index',
            component: '/seller/app/home/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '首页图管理',
            },
            name: 'ViewsSysEmpUserIndex',
            leaf: false,
            url: '/seller/app/home/index',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '小程序管理',
        },
        name: 'ViewsSellerGoodsIndex',
        leaf: false,
        url: '/seller/goods/index',
        target: '',
      },
      {
        path: '/seller/members',
        redirect: '/seller/members/user/index',
        component: 'LAYOUT',
        children: [
          {
            path: '/seller/members/user/index',
            component: '/seller/members/user/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '会员管理',
            },
            name: 'ViewsSellerMembersUserIndex',
            leaf: false,
            url: '/seller/members/user/index',
            target: '',
          },
          {
            path: '/seller/members/stored-value/index',
            component: '/seller/members/storedValue/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '会员储值',
            },
            name: 'ViewsSellerMembersStoredValueIndex',
            leaf: false,
            url: '/seller/members/stored-value/index',
            target: '',
          },
          {
            path: '/seller/members/tag/index',
            component: '/seller/members/tag/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '会员标签',
            },
            name: 'ViewsSellerMembersTagIndex',
            leaf: false,
            url: '/seller/members/tag/index',
            target: '',
          },
          {
            path: '/seller/members/group/index',
            component: '/seller/members/group/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '会员分组',
            },
            name: 'ViewsSellerMembersGroupIndex',
            leaf: false,
            url: '/seller/members/group/index',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '会员中心',
        },
        name: 'ViewsSellerMembersCenter',
        leaf: false,
        url: '/seller/members',
        target: '',
      },
      {
        path: '/seller/order',
        redirect: '/seller/order/list/index',
        component: 'LAYOUT',
        children: [
          {
            path: '/seller/order/list/index',
            component: '/seller/order/list/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '订单列表',
            },
            name: 'ViewsSellerOrderListIndex',
            leaf: false,
            url: '/seller/order/list/index',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '订单中心',
        },
        name: 'ViewsSellerOrderIndex',
        leaf: false,
        url: '/seller/order',
        target: '',
      },
      {
        path: '/seller/product',
        redirect: '/seller/product/list/index',
        component: 'LAYOUT',
        children: [
          {
            path: '/seller/product/list/index',
            component: '/seller/product/list/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '商品列表',
            },
            name: 'ViewsSellerProductListIndex',
            leaf: false,
            url: '/seller/product/list/index',
            target: '',
          },
          {
            path: '/seller/product/comment/index',
            component: '/seller/product/comment/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '商品评论',
            },
            name: 'ViewsSellerProductCommentIndex',
            leaf: false,
            url: '/seller/product/comment/index',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '商品中心',
        },
        name: 'ViewsSellerProductIndex',
        leaf: false,
        url: '/seller/product/index',
        target: '',
      },
      {
        path: '/seller/store/index',
        component: '/seller/store/index',
        children: [],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '门店管理',
        },
        name: 'ViewsSellerStoreIndex',
        leaf: false,
        url: '/seller/store/index',
        target: '',
      },
      {
        path: '/seller/coupon/index',
        redirect: '/seller/coupon/list/index',
        component: 'LAYOUT',
        children: [
          {
            path: '/seller/coupon/list/index',
            component: '/seller/coupon/list/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '优惠券列表',
            },
            name: 'ViewsSellerCouponListIndex',
            leaf: false,
            url: '/seller/coupon/list/index',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '优惠券中心',
        },
        name: 'miewsSellerCouponIndex',
        leaf: false,
        url: '/seller/coupon/index',
        target: '',
      },
      {
        path: '/seller/statistics',
        redirect: '/seller/statistics/member/index',
        component: 'LAYOUT',
        children: [
          {
            path: '/seller/statistics/member/index',
            component: '/seller/statistics/member/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '会员统计',
            },
            name: 'miewsSellerStatisticsMemberIndex',
            leaf: false,
            url: '/seller/statistics/member/index',
            target: '',
          },
          {
            path: '/seller/statistics/trade/index',
            component: '/seller/statistics/trade/index',
            children: [],
            meta: {
              icon: 'icon-grid',
              hideMenu: false,
              color: '',
              title: '交易统计',
            },
            name: 'miewsSellerStatisticsTradeIndex',
            leaf: false,
            url: '/seller/statistics/trade/index',
            target: '',
          },
        ],
        meta: {
          icon: 'icon-grid',
          hideMenu: false,
          color: '',
          title: '统计中心',
        },
        name: 'miewsSellerStatisticsIndex',
        leaf: false,
        url: '/seller/statistics',
        target: '',
      },
    ],
    leaf: false,
    url: '',
    target: '',
  },
];
